src/models/__init__.py
from .user import User
from .game import Game

src/models/game.py
from src.database import db


class Game(db.Model):
    __tablename__ = 'games'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(100), nullable=False)
    category = db.Column(db.String(100), nullable=False)
    console = db.Column(db.String(100), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, name, category, console, user_id):
        self.name = name
        self.category = category
        self.console = console
        self.user_id = user_id

    def __repr__(self):
        return '<id {}>'.format(self.id)

    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'category': self.category,
            'console': self.console
        }

src/models/user.py
from src.database import db


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    games = db.relationship('Game', backref='users', lazy=True)

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.password = password

    def __repr__(self):
        return '<id {}>'.format(self.id)

    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'email': self.email,
            'password': self.password
        }

src/__init__.py
from flask import Flask
from .database import db, migrate
from .routes import *
from .models import *
import os

app = Flask(__name__)
app.secret_key = '!@#Chave_muito_segura_kkjkk!@#'
app.config.from_object(os.environ['APP_SETTINGS'])
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


db.init_app(app)
migrate.init_app(app, db)

app.register_blueprint(routes)
with app.app_context():
    db.create_all()
app.run(debug=True)

src/controllers/game.py
from flask import render_template, redirect, request, session, flash, jsonify
from flask.helpers import url_for
from src.database import db
from src.models import Game


def renderNewGame():
    title: str = "Criar Jogo"
    return render_template('newGame.html', title=title)


def createGame():
    name: str = request.form['name']
    category: str = request.form['category']
    console: str = request.form['console']
    user_id: int = session['user_id']

    try:
        game = Game(
            name=name,
            category=category,
            console=console,
            user_id=user_id
        )
        db.session.add(game)
        db.session.commit()
        flash('Jogo de ID {} adicionado'.format(game.id))
        return redirect(url_for('routes.indexUserRoute'))
    except Exception as exception:
        return(str(exception))


def renderListGames():
    games = getAllGames(session['user_id'])
    return render_template('listGames.html', games=games)


def getAllGames(user_id):
    return Game.query.filter_by(user_id=user_id)


def getGameById(id_):
    try:
        game = Game.query.filter_by(id=id_).first()
        return jsonify(game.serialize())
    except Exception as exception:
        return(str(exception))

src/controllers/user.py
from flask import render_template, request, redirect, session, flash
from flask.helpers import url_for
from src.database import db
from src.models import User
import bcrypt


def renderIndex():
    title: str = "Página Inicial"
    return render_template('index.html', title=title)


def renderIndexUser():
    title: str = "Página Inicial"
    return render_template('indexUser.html', title=title)


def renderLogin():
    title: str = "Login"
    return render_template('login.html', title=title)


def renderRegister():
    title: str = "Cadastro"
    return render_template('register.html', title=title)


def logout():
    session['email'] = None
    session['user_id'] = None
    flash('Usuário não logado')
    return redirect(url_for('routes.indexRoute'))


def authenticate():
    email: str = request.form['email']
    password: str = request.form['password']
    users = User.query.all()
    for user in users:
        if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')) and email == user.email:
            session['email'] = user.email
            session['user_id'] = user.id
            flash(session['email'] + ' logado com sucesso!')
            return redirect(url_for('routes.indexUserRoute'))
        else:
            flash('Senha ou E-mail incorretos')
            return redirect(url_for('routes.indexRoute'))


def createUser():
    name: str = request.form['name']
    email: str = request.form['email']
    password = bcrypt.hashpw(request.form['password'].encode('utf-8'), bcrypt.gensalt())
    try:
        user = User(
            name=name,
            email=email,
            password=password.decode('utf-8')
        )
        db.session.add(user)
        db.session.commit()
        flash('Cadastro realizado com sucesso')
        return redirect(url_for('routes.loginRoute'))
    except Exception as exception:
        return(str(exception))

src/database/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()

src/routes/__init__.py
from flask import Blueprint
routes = Blueprint('routes', __name__)

from .game import *
from .user import *

src/routes/game.py
from . import routes
from src.controllers.game import *


@routes.route('/newGame', methods=['GET'])
def newGameRoute():
    return renderNewGame()


@routes.route('/createGame', methods=['POST'])
def createGameRoute():
    return createGame()


@routes.route('/listGame', methods=['GET'])
def listGameRoute():
    return renderListGames()

src/routes/user.py
from . import routes
from src.controllers.user import *


@routes.route('/', methods=['GET'])
def indexRoute():
    return renderIndex()


@routes.route('/indexUser', methods=['GET'])
def indexUserRoute():
    return renderIndexUser()


@routes.route('/login', methods=['GET'])
def loginRoute():
    return renderLogin()


@routes.route('/logout', methods=['GET'])
def logoutRoute():
    return logout()


@routes.route('/authenticate', methods=['POST'])
def authenticateRoute():
    return authenticate()


@routes.route('/register', methods=['GET'])
def registerRoute():
    return renderRegister()


@routes.route('/register', methods=['POST'])
def registerUserRoute():
    return createUser()

src/templates/index.html
{% extends "template.html" %}
{% block content %}
    <div class="row">
        <h3> <a href="{{url_for('routes.loginRoute')}}"> Login </a> </h3>
        <h3> <a href="{{url_for('routes.registerRoute')}}"> Cadastro </a> </h3>
    </div>
{% endblock %}

src/templates/indexUser.html
{% extends "template.html" %}
{% block content %}
    <div class="row">
        <h3> <a href="{{url_for('routes.listGameRoute')}}"> Listar jogos </a> </h3>
        <h3> <a href="{{url_for('routes.newGameRoute')}}"> Criar jogos </a> </h3>
        <h3> <a href="{{url_for('routes.logoutRoute')}}"> Sair </a> </h3>
    </div>
{% endblock %}

src/templates/listGames.html
{% extends "template.html" %}
{% block content %}
    <div class="row">
        <h3> Lista de Jogos </h3>
        <table class="table table-striped table-responsive table-border">
            <thead class="thead-default">
                <tr> 
                    <td> Nome </td>     
                    <td> Categoria </td> 
                    <td> Console </td> 
                </tr>
            </thead>
            <tbody>
                {% for game in games %}
                    <tr> 
                        <td> {{ game.name }}</td>     
                        <td> {{ game.category }}</td> 
                        <td> {{ game.console }}</td> 
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

src/templates/login.html
{% extends "template.html" %}
{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %} 
            <ul id="messages" class="list-unstyled">
                {% for message in messages %}
                    <li class="alert alert-success">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <form action="{{url_for('routes.authenticateRoute')}}" method="POST">
        <fieldset>
            <div class="form-group">
                <label for="email"> E-mail </label>
                <input type="email" id="email" name="email" class="form-control">
            </div>
            <div class="form-group">
                <label for="password"> Senha </label>
                <input type="password" id="password" name="password" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary btn-salvar"> Salvar </button>
        </fieldset>
    </form>
{% endblock %}

src/templates/newGame.html
{% extends "template.html" %}
{% block content %}
    <form action="{{url_for('routes.createGameRoute')}}" method="POST">
        <fieldset>
            <div class="form-group">
                <label for="name"> Nome </label>
                <input type="text" id="name" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="category"> Categoria </label>
                <input type="text" id="category" name="category" class="form-control">
            </div>
            <div class="form-group">
                <label for="console"> Console </label>
                <input type="text" id="console" name="console" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary btn-salvar"> Salvar </button>
        </fieldset>
    </form>
{% endblock %}

src/templates/register.html
{% extends "template.html" %}
{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %} 
            <ul id="messages" class="list-unstyled">
                {% for message in messages %}
                    <li class="alert alert-success">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <form action="{{url_for('routes.registerUserRoute')}}" method="POST">
        <fieldset>
            <div class="form-group">
                <label for="name"> Nome </label>
                <input type="text" id="name" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="email"> E-mail </label>
                <input type="email" id="email" name="email" class="form-control">
            </div>
            <div class="form-group">
                <label for="password"> Senha </label>
                <input type="password" id="password" name="password" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary btn-salvar"> Salvar </button>
        </fieldset>
    </form>
{% endblock %}

src/templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XGames</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="page-header">
            <h1> {{title}} </h1>
        </div>
        {% block content %} {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends "template.html" %}
{% block content %}
    <div class="row">
        <h3> <a href="/login"> Login </a> </h3>
        <h3> <a href="/"> Cadastro </a> </h3>
    </div>
{% endblock %}

templates/login.html
{% extends "template.html" %}
{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %} 
            <ul id="messages" class="list-unstyled">
                {% for message in messages %}
                    <li class="alert alert-success">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <form action="{{url_for('authenticate')}}" method="POST">
        <fieldset>
            <div class="form-group">
                <label for="email"> E-mail </label>
                <input type="email" id="email" name="email" class="form-control">
            </div>
            <div class="form-group">
                <label for="password"> Senha </label>
                <input type="password" id="password" name="password" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary btn-salvar"> Salvar </button>
        </fieldset>
    </form>
{% endblock %}

templates/newGame.html
{% extends "template.html" %}
{% block content %}
    <form action="{{url_for('createGame')}}" method="POST">
        <fieldset>
            <div class="form-group">
                <label for="name"> Nome </label>
                <input type="text" id="name" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="category"> Categoria </label>
                <input type="text" id="category" name="category" class="form-control">
            </div>
            <div class="form-group">
                <label for="console"> Console </label>
                <input type="text" id="console" name="console" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary btn-salvar"> Salvar </button>
        </fieldset>
    </form>
{% endblock %}
    